name: waterwalk
main: cc.art.bukkit.skills.Main
version: alpha0.1
author: Arthurdes
description: if walk on water,water trun ice
permissions:
  art.test:
    description: non
    default: false